version: "3"

services:
  nostr-scraper:
    build: .
    environment:
      INPUT_RELAY: wss://relay.nostr.band
      OUTPUT_RELAY: ws://relay:8080
      KINDS: "[0,1]"
    restart: always
    depends_on:
      - relay
      - postgres
  relay:
    # image: ghcr.io/mroxso/nostr-rs-relay:latest
    image: scsibug/nostr-rs-relay:latest
    container_name: relay
    user: "100:100"
    ports:
      - 8080:8080
    volumes:
      - ./data:/usr/src/app/db:Z
      - ./config.toml:/usr/src/app/config.toml
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: justasimplepassword
      POSTGRES_USER: nostr
      POSTGRES_DB: nostr
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:Z
    ports:
      - 5432:5432