version: "3"

services:
  nostr-scraper:
    build: .
    environment:
      INPUT_RELAY: wss://relay.nostr.band
      OUTPUT_RELAY: ws://relay:8080
    restart: always
    depends_on:
      - relay
  relay:
    # image: ghcr.io/mroxso/nostr-rs-relay:latest
    image: scsibug/nostr-rs-relay:latest
    user: "100:100"
    ports:
      - 8080:8080
    volumes:
      - ./data:/usr/src/app/db:Z
      - ./config.toml:/usr/src/app/config.toml